version : '3'

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: Novirus123!
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    restart: always
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8080:80

  api:
    build: ./api
    container_name: inv
    depends_on:
      - mysql
    links:
      - mysql
    restart: always
    ports:
      - 8082:80
    command: ["gunicorn", "-b", "0.0.0.0:80", "server:app"]
  
  web_app:
    build: ./web_app
    container_name: web_app
    depends_on:
      - api
    restart: always
    ports:
      - 8081:80
    command: ["nginx", "-g", "daemon off;"]